<script type="text/javascript" src="js/lib/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="js/lib/jquery.md5.min.js"></script>
<script type="text/javascript" src="js/common.js"></script>
<script type="text/javascript">

	function showOverlay (title) {
		if (!title) {
			title = '';
		}
		$('.overlay-title').text(title);
		$('.overlay-container').fadeIn();
	}

	$(function () {
		$('.overlay-container').on('click', function () {
			$(this).fadeOut();
		});

		$('.overlay-wrapper').on('click', function (e) {
			e.preventDefault();
			e.stopPropagation();
			return false;
		});
	});

</script>
