<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="apple-touch-icon" href="images/logo.png">
    <title>Example Client</title>
    <meta id="viewport" name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">

    <link rel="stylesheet" type="text/css" href="css/flexslider.css">
    <link rel="stylesheet" type="text/css" href="css/animate.css">
    <link rel="stylesheet" type="text/css" href="css/shake.css">
    <link rel="stylesheet" type="text/css" href="css/main.css">

    <?php
    if (empty($data['nowechat'])) {
        include APP_DIR.DS.'view'.DS.'mobile'.DS.'public'.DS.'scripts.phtml';
    } else {
        include APP_DIR.DS.'view'.DS.'mobile'.DS.'public'.DS.'scripts-nowechat.phtml';
    }
    ?>
</head>
<body>
	<?php include APP_DIR.DS.'view'.DS.'mobile'.DS.'public'.DS.'navigation.phtml'; ?>
    <div class="page-container">
